<!--
SPDX-FileCopyrightText: 2025 Np-93/237 (Yretenai/Legiayayana/Chronovore)

SPDX-License-Identifier: MIT
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DragonLib\DragonLib\DragonLib.csproj"/>
		<ProjectReference Include="..\..\Shard.SDK\Shard.SDK.csproj"/>
	</ItemGroup>

</Project>
